#!/bin/dash

# colors

black=#1e1e2e
white=#D9E0EE
grey=#282737
purple=#cba6f7
blue=#96CDFB
darkblue=#83bae8

pink=#f5c2e7
mauve=#cba6f7
red=#f38ba8
maroon=#eba0ac
peach=#fab387
yellow=#f9e2af
green=#a6e3a1
